/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <STM32F407xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t delay;
	// Wlaczenie zegara magistrali AHB1 dla portu PORTD
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	// Ustawienie linii 12 portu D jako wyjscia (LSB->1)
	GPIOD->MODER |= GPIO_MODER_MODER12_0;
	// (MSB->0)
	GPIOD->MODER &= ~GPIO_MODER_MODER12_1;
	// Ustawienie typu wyjscia
	GPIOD->OTYPER &= ~GPIO_OTYPER_OT12;
	// Ustawienie szybkosci linii portu
	GPIOD->OSPEEDR &= ~(GPIO_OSPEEDR_OSPEED12_0 | GPIO_OSPEEDR_OSPEED12_1);
	// Ustawienie rezystorow Pull-up/Pull-down
	GPIOD->PUPDR &= ~GPIO_PUPDR_PUPD12_Msk;
	/* Loop forever */
	for(;;) {
		for (delay=0;delay<200000;delay++);
		// Zerowanie bitu odpowiadajacego wyjsciu PD12
		GPIOD->BSRR |= GPIO_BSRR_BR12;
		for (delay=0;delay<200000;delay++);
		// Ustawiania bitu odpowiadajacego wyjsciu PD12
		GPIOD->BSRR |= GPIO_BSRR_BS12;
	};
}

