[package]
name = "lab04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.5"
rustfft = "6.2.0"
num-complex = "0.4.0"
lerp = "0.5.0"
